---


version: "3.7"
services:
  zyte-proxy-headless-proxy:
    image: zyte-proxy-headless-proxy
    build: .
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 5s
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    environment:
      ZYTE_PROXY_HEADLESS_APIKEY: USER_API_KEY
    ports:
      - target: 3128
        published: 3128
        protocol: tcp
